trigger: none
# trigger:
#  branches:
#    include:
#      - main
#  paths:
#    include:
#      - 03-service-objects/*
pool:
  name: devopspool1
  #name: Azure Pipelines

variables:
  tfFolder: 03-service-objects
  azureServiceConnection: sp-avd-lab
  deploymentSubscriptionId: e4ea360b-bf76-47bc-bb09-81bd23faad9e
  stateSubscriptionId: eb60ae18-0772-4810-8616-c189bb571c25
  backendResourceGroupName: rg-tfstore
  backendStorageAccountName: tfstore101

parameters:
  - name: doDestroy
    displayName: Destroy resources
    type: boolean
    default: false

  - name: deployNpd
    displayName: 'Environment: NPD'
    type: boolean
    default: true

  - name: deployTst
    displayName: 'Environment: TST'
    type: boolean
    default: false

  - name: deployPrd
    displayName: 'Environment: PRD'
    type: boolean
    default: false

stages:
  - template: ../_common/terraform-plan-apply.yml
    parameters:
      stageName: NPD
      environmentName: npd
      doDestroy: ${{ parameters.doDestroy }}
      azureServiceConnection: $(azureServiceConnection)
      deploymentSubscriptionId: $(deploymentSubscriptionId)
      stateSubscriptionId: $(stateSubscriptionId)
      backendResourceGroupName: $(backendResourceGroupName)
      backendStorageAccountName: $(backendStorageAccountName)
      backendStateKey: npd-$(tfFolder).tfstate
      terraformCommonVarFile: ../_environment/npd.tfvars
      terraformVarFile: npd.tfvars
      terraformWorkingDirectory: $(System.DefaultWorkingDirectory)/$(tfFolder)
      runStage: ${{ parameters.deployNpd }}

  - template: ../_common/terraform-plan-apply.yml
    parameters:
      stageName: TST
      environmentName: tst
      dependsOn: NPD
      doDestroy: ${{ parameters.doDestroy }}
      azureServiceConnection: $(azureServiceConnection)
      deploymentSubscriptionId: $(deploymentSubscriptionId)
      stateSubscriptionId: $(stateSubscriptionId)
      backendResourceGroupName: $(backendResourceGroupName)
      backendStorageAccountName: $(backendStorageAccountName)
      backendStateKey: tst-$(tfFolder).tfstate
      terraformCommonVarFile: ../_environment/tst.tfvars
      terraformVarFile: tst.tfvars
      terraformWorkingDirectory: $(System.DefaultWorkingDirectory)/$(tfFolder)
      runStage: ${{ parameters.deployTst }}

  - template: ../_common/terraform-plan-apply.yml
    parameters:
      stageName: PRD
      environmentName: prd
      dependsOn: TST
      doDestroy: ${{ parameters.doDestroy }}
      azureServiceConnection: $(azureServiceConnection)
      deploymentSubscriptionId: $(deploymentSubscriptionId)
      stateSubscriptionId: $(stateSubscriptionId)
      backendResourceGroupName: $(backendResourceGroupName)
      backendStorageAccountName: $(backendStorageAccountName)
      backendStateKey: prd-$(tfFolder).tfstate
      terraformCommonVarFile: ../_environment/prd.tfvars
      terraformVarFile: prd.tfvars
      terraformWorkingDirectory: $(System.DefaultWorkingDirectory)/$(tfFolder)
      runStage: ${{ parameters.deployPrd }}