parameters:
  tfFolder: ''
  doDestroy: false
  deployNpd: true
  deployUat: false
  deployPrd: false
  npdAzureServiceConnection: sp-avd-lab
  uatAzureServiceConnection: sp-avd-lab-uat
  prdAzureServiceConnection: sp-avd-lab-prd

stages:
  - ${{ if eq(parameters.deployNpd, true) }}:
      - template: terraform-plan-apply.yml
        parameters:
          stageName: NPD
          environmentName: npd
          variableTemplate: ../_environment/vars-npd.yml
          azureServiceConnection: ${{ parameters.npdAzureServiceConnection }}
          doDestroy: ${{ parameters.doDestroy }}
          backendStateKey: npd-${{ parameters.tfFolder }}.tfstate
          terraformCommonVarFile: ../_environment/npd.tfvars
          terraformVarFile: npd.tfvars
          terraformWorkingDirectory: $(System.DefaultWorkingDirectory)/${{ parameters.tfFolder }}
          runStage: true

  - ${{ if eq(parameters.deployUat, true) }}:
      - template: terraform-plan-apply.yml
        parameters:
          stageName: UAT
          environmentName: uat
          variableTemplate: ../_environment/vars-uat.yml
          azureServiceConnection: ${{ parameters.uatAzureServiceConnection }}
          doDestroy: ${{ parameters.doDestroy }}
          backendStateKey: uat-${{ parameters.tfFolder }}.tfstate
          terraformCommonVarFile: ../_environment/uat.tfvars
          terraformVarFile: uat.tfvars
          terraformWorkingDirectory: $(System.DefaultWorkingDirectory)/${{ parameters.tfFolder }}
          runStage: true

  - ${{ if eq(parameters.deployPrd, true) }}:
      - template: terraform-plan-apply.yml
        parameters:
          stageName: PRD
          environmentName: prd
          variableTemplate: ../_environment/vars-prd.yml
          azureServiceConnection: ${{ parameters.prdAzureServiceConnection }}
          doDestroy: ${{ parameters.doDestroy }}
          backendStateKey: prd-${{ parameters.tfFolder }}.tfstate
          terraformCommonVarFile: ../_environment/prd.tfvars
          terraformVarFile: prd.tfvars
          terraformWorkingDirectory: $(System.DefaultWorkingDirectory)/${{ parameters.tfFolder }}
          runStage: true
