rg_so                           = "rg-service-objects-npd"
keyvault_name                   = "kv-avd-itm-npd"
rg_network                      = "rg-itm-network-npd"
vnet_name                       = "vnet-itm-vnet-npd"
pesubnet_keyvault               = "snet-general-pe"
keyvault_pe_name                = "keyvault-pe-npd"
keyvault_sc_name                = "keyvault-sc-npd"
avd_service_principal_object_id = "66080947-954d-4adb-933c-293d3bbb3441"
