trigger: none
# trigger:
#  branches:
#    include:
#      - main
#  paths:
#    include:
#      - avd-terraform4/00-inplace-network/*

pool:
  name: devopspool1
  #name: Azure Pipelines

variables:
  tfFolder: 00-inplace-network

parameters:
  - name: doPause
    type: boolean
    default: false
  - name: doDestroy
    type: boolean
    default: false
  - name: env
    displayName: Select environment
    type: string
    default: 'npd'
    values:
      - npd
      - tst
      - prd

stages:
  - template: ../_common/terraform-plan-apply.yml
    parameters:
      environmentName:            '${{ parameters.env }}'
      azureServiceConnection:     'sp-avd-lab'
      deploymentSubscriptionId:   'e4ea360b-bf76-47bc-bb09-81bd23faad9e'
      backendStateKey:            '${{ parameters.env }}-$(tfFolder).tfstate'

      doPause:                    '${{ parameters.doPause }}'
      doDestroy:                  '${{ parameters.doDestroy }}'
      env:                        '${{ parameters.env }}'

      terraformVarFile:           '../${{ parameters.env }}.tfvars'
      tfVariablesFile:            '../variables.tf'    
      terraformWorkingDirectory:  '$(System.DefaultWorkingDirectory)/$(tfFolder)'
      stateSubscriptionId:        'eb60ae18-0772-4810-8616-c189bb571c25'
      backendResourceGroupName:   'rg-tfstore'
      backendStorageAccountName:  'tfstore101'
      