trigger: none
# trigger:
#  branches:
#    include:
#      - main
#  paths:
#    include:
#      - 05-hostpool/*
pool:
  name: devopspool1
  #name: Azure Pipelines

parameters:
  - name: doDestroy
    displayName: Destroy resources
    type: boolean
    default: false

  - name: deployNpd
    displayName: 'Environment: NPD'
    type: boolean
    default: true

  - name: deployTst
    displayName: 'Environment: TST'
    type: boolean
    default: false

  - name: deployPrd
    displayName: 'Environment: PRD'
    type: boolean
    default: false

stages:
  - template: ../_common/terraform-environments.yml
    parameters:
      tfFolder: 05-hostpool
      doDestroy: ${{ parameters.doDestroy }}
      deployNpd: ${{ parameters.deployNpd }}
      deployTst: ${{ parameters.deployTst }}
      deployPrd: ${{ parameters.deployPrd }}
